plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.pobedaradar.app'
    compileSdk 35

    defaultConfig {
        applicationId "ru.pobedaradar.app"
        minSdk 26
        targetSdk 35
        versionCode 8
        versionName "0.8"
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation "androidx.work:work-runtime:2.11.2"
}
