plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.pobedaradar.app'
    compileSdk 35

    signingConfigs {
        permanent {
            storeFile file("${rootProject.projectDir}/pobedaradar-release.jks")
            storePassword "OzK5!uQAqG37aeBEl8wg4yWxXrqF"
            keyAlias "pobedaradar"
            keyPassword "OzK5!uQAqG37aeBEl8wg4yWxXrqF"
        }
    }

    defaultConfig {
        applicationId "ru.pobedaradar.app"
        minSdk 26
        targetSdk 35

        versionCode 13
        versionName "0.13"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.permanent
        }
    }
}

dependencies {
    implementation "androidx.work:work-runtime:2.11.2"
    implementation "androidx.core:core:1.15.0"
}
